version: "3.9"
services:
  auth:
    hostname: auth
    build: ./auth
    ports:
      - 8081:5000
    environment:
      HOST_NAME: postgres
      AUTH_DB_NAME: auth
      PORTFOLIOS_DB_NAME: portfolios
      DB_USER: user
      DB_PASSWORD: password
      AUTH_SECRET: secret
      EXPIRE_TIME_SEC: 3000

  trading-platform:
    hostname: trading-platform
    build: ./platform
    ports:
      - 8082:5000

# TODO different credentials
  portfolio-mgmt:
    hostname: portfolio-mgmt
    build: ./portfolio-mgmt
    environment:
      HOST_NAME: postgres
      DB_NAME: portfolios 
      DB_USER: user
      DB_PASSWORD: password

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data: