{
 "title": "Loki (logging)",
 "description": "Logs from Auth Service and Trading Platform",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Auth Service Requests",
   "type": "logs",
   "description": "Logs that contain requests sent from Auth Service to other services.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{swarm_service=\"trading-platform_auth\"} |~ `INFO: [0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+`"
    }
   ]
  },
  {
   "title": "Auth Service Log",
   "type": "logs",
   "description": "Log for Auth Service's INFO and ERROR level messages.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{swarm_service=\"trading-platform_auth\"} |~ `(INFO|ERROR)` != `CTRL+C` != `This is a development server.` !~ `INFO: [0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+`"
    }
   ]
  },
  {
   "title": "Auth Service Debug Log",
   "type": "logs",
   "description": "Panel that contains logs from all levels.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{swarm_service=\"trading-platform_auth\"} |= ``"
    }
   ]
  },
  {
   "title": "Trading Platform Requests",
   "type": "logs",
   "description": "Logs that contain HTTP requests sent to Trading Platform and from Trading Platform to other services.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{swarm_service=\"trading-platform_trading-platform\"} |~ `INFO: [0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+`"
    }
   ]
  },
  {
   "title": "Trading Platform Log",
   "type": "logs",
   "description": "Log for Trading Platform's INFO and ERROR level messages.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{swarm_service=\"trading-platform_trading-platform\"} |~ `(INFO|ERROR)` != `CTRL+C` != `This is a development server.` !~ `INFO: [0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+`"
    }
   ]
  },
  {
   "title": "Trading Platform Debug Log",
   "type": "logs",
   "description": "Panel that contains logs from all levels.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{swarm_service=\"trading-platform_trading-platform\"} |= ``"
    }
   ]
  }
 ]
}